$env:GPU_SERVICE_PORT = "26200"
$env:GPU_SERVICE_METRICS_PORT = "27200"
$env:TRAIN_PROFILES = "4"
$env:NUM_GAME_RUNNERS = "24"
$env:TOTAL_EPISODES = "5000000"
$env:PY_BATCH_TIMEOUT_MS = "25"
$env:PY_SERVICE_MODE = "shared_gpu"
$env:CUDA_MEM_FRACTION = "0.5"
$env:USE_TRT_INFERENCE = "1"
$env:INFER_SERVICE_ENDPOINT = ""
$env:TRAIN_CUDA_DEVICE = "cpu"
$env:PPO_VF_CLIP = "0"
$env:CRITIC_LR = "5e-4"
$env:ENTROPY_START = "0.15"
$env:ENTROPY_END = "0.02"
$env:ENTROPY_DECAY_STEPS = "500000"
$env:ORCHESTRATED_RUN = "1"
$env:GAME_LOG_FREQUENCY = "500"
$env:WINRATE_WINDOW = "200"
$env:PBT_EXPLOIT_INTERVAL = "60"
$env:PBT_MIN_EPISODES = "200"

$env:PYTHONUNBUFFERED = "1"
$env:MAVEN_OPTS = "-Xmx8g -Xms4g -XX:+UseG1GC -XX:MaxGCPauseMillis=50"

Set-Location "C:\Users\haley\mage"
New-Item -ItemType Directory -Path "local-training\local_pbt" -Force | Out-Null
py -3.12 scripts/run_local_pbt.py 2>&1 | Tee-Object -FilePath "local-training\local_pbt\training_console.log"
